name: supplier
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  go_router: ^9.1.0
  riverpod_annotation: ^2.1.1
  flutter_svg:
  font_awesome_flutter:
  lottie:
  google_fonts:
  intl:
  flutter_animate:
  fixnum:
  shimmer:
  flutter_slidable:
  flutter_staggered_animations:
  protobufs:
    path: ../protobufs

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2

flutter:
  uses-material-design: true
  assets:
   - assets/images/
  fonts:
    - family: grifterbold
      fonts:
        - asset: assets/fonts/grifterbold.otf

